// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

library Contributors {
    /** @dev This library is generated by the script `generate-contributors.js`.
        @dev An allocation of type(uint56).max means 100% of the issuance reserved for contributors. 
        @dev Sum of all allocations should be equal to type(uint56).max or less.
    */
    function getAllocation(address contributor) internal pure returns (uint56) {
        if (contributor == address(0x0000000000000000000000000000000000000011)) return 22912059411461612;
        else if (contributor == address(0x0000000000000000000000000000000000000012)) return 68736178234385;
        else if (contributor == address(0x0000000000000000000000000000000000000013)) return 22912059411462;
        else if (contributor == address(0x0000000000000000000000000000000000000014)) return 11456029705730806;
        else if (contributor == address(0x0000000000000000000000000000000000000015)) return 1583223305331997;
        else if (contributor == address(0x0000000000000000000000000000000000000016)) return 9781158162752962;
        else if (contributor == address(0x0000000000000000000000000000000000000001)) return 1500560574462087;
        else if (contributor == address(0x0000000000000000000000000000000000000002)) return 18006726893545044;
        else if (contributor == address(0x0000000000000000000000000000000000000003)) return 6726187746997582;
        
        return 0;
    }
}
