// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

library Contributors {
    /** @dev This library is generated by the script \`generate-contributors.js\`.
        @dev Sum of all allocations: 31.87% of total supply
        @dev An allocation of type(uint56).max means 100% of the issuance reserved for non-LPers.
        @dev Sum of all allocations should be equal to type(uint56).max or less.
    */
    function getAllocation(address contributor) internal pure returns (uint56) {
        if (contributor == address(0x1234567890123456789012345678901234567890)) return 7205759403792794;
        else if (contributor == address(0x0000000000000000000000000000000000000001)) return 5764607523034235;
        else if (contributor == address(0x0000000000000000000000000000000000000002)) return 1801439850948199;
        else if (contributor == address(0x36D11126eBc59cb962AE8ddD3bcD0741b4e337Dc)) return 1724741747854228;
        else if (contributor == address(0x30E14c4b4768F9B5F520a2F6214d2cCc21255fDa)) return 936748722493063;
        else if (contributor == address(0x0000000000000000000000000000000000000003)) return 720575940379279;
        else if (contributor == address(0xfdcc69463b0106888D1CA07CE118A64AdF9fe458)) return 720575940379279;
        else if (contributor == address(0x0000000000000000000000000000000000000004)) return 504403158265496;
        else if (contributor == address(0x26610e89A8B825F23E89e58879cE97D791aD4438)) return 360287970189640;
        else if (contributor == address(0x79C1134a1dFdF7e0d58E58caFC84a514991372e6)) return 338353638564494;
        else if (contributor == address(0xFe202706E36F31aFBaf4b4543C2A8bBa4ddB2deE)) return 322818021289917;
        else if (contributor == address(0x8D2a097607da5E2E3d599c72EC50FD0704a4D37f)) return 299665916325531;
        else if (contributor == address(0x3424cd7D170949636C300e62674a3DFB7706Fc35)) return 281024616747919;
        else if (contributor == address(0x18e17dd452Ef58F91E45fD20Eb2F839ac13AA648)) return 216172782113784;
        else if (contributor == address(0x78086Ad810f8F99A0B6c92a9A6c8857d3c665622)) return 172080740321976;
        else if (contributor == address(0xEdA726014938d2E6Ed51c7d5A53193cf9713cdF7)) return 150240083569080;
        else if (contributor == address(0xE19618C08F74b7e80278Ec14b63797419dACCDf8)) return 144115188075856;
        else if (contributor == address(0xde3697dDA384ce178d04D8879F7a66423F72A326)) return 113440270293910;
        else if (contributor == address(0x0000000000000000000000000000000000000005)) return 108086391056892;
        else if (contributor == address(0x241F1A461Da47Ccd40B48c38340896A9948A4725)) return 102970301880199;
        else if (contributor == address(0x32cf4d1df6fb7bB173183CF8b51EF9499c803634)) return 97890241500525;
        else if (contributor == address(0xa485B739e99334f4B92B04da2122e2923a054688)) return 93674872249306;
        else if (contributor == address(0x1ff241abaD54DEcB967Bd0f57c2a584C7d1ca8BD)) return 86469112845514;
        else if (contributor == address(0x7DF76FDEedE91d3cB80e4a86158dD9f6D206c98E)) return 81122439367899;
        else if (contributor == address(0xBA5EDc0d2Ae493C9574328d77dc36eEF19F699e2)) return 73354630730611;
        else if (contributor == address(0x0000000000000000000000000000000000000007)) return 72057594037928;
        else if (contributor == address(0xA6f4fa9840Aa6825446c820aF6d5eCcf9f78BA05)) return 51953525301346;
        else if (contributor == address(0xa233f74638Bd28A24CC2Ce23475eea7dC76881AC)) return 37503095392980;
        else if (contributor == address(0x0000000000000000000000000000000000000008)) return 36028797018964;
        else if (contributor == address(0x0000000000000000000000000000000000000009)) return 36028797018964;
        else if (contributor == address(0x16fD74300dcDc02E9b1E594f293c6EfFB299a3fc)) return 36028797018964;
        else if (contributor == address(0xbe1E110f4A2fD54622CD516e86b29f619ad994bF)) return 34378678115495;
        else if (contributor == address(0xdF58360e945F6a302FFFB012D114C9e2bE2F212a)) return 28390692050944;
        else if (contributor == address(0x65a831D9fB2CC87A7956eB8E4720956f6bfC6eeA)) return 27802702083594;
        else if (contributor == address(0x6422D607CA13457589A1f2dbf0ec63d5Adf87BFB)) return 26084849041730;
        else if (contributor == address(0x0D5f69C67DAE06ce606246A8bd88B552d1DdE140)) return 21617278211378;
        else if (contributor == address(0xF613cfD07af6D011fD671F98064214aB5B2942CF)) return 21473163023303;
        else if (contributor == address(0xc4Ab0e3F12309f37A5cdf3A4b3B7C70A53eeBBa9)) return 20088216065894;
        else if (contributor == address(0xAacc079965F0F9473BF4299d930eF639690a9792)) return 18734974449861;
        else if (contributor == address(0x81B55FBe66C5FFbb8468328E924AF96a84438F14)) return 18014398509482;
        else if (contributor == address(0xb1f55485d7ebA772F0d454Ceb0EA9a27586Ad86f)) return 17005592192951;
        else if (contributor == address(0x1C5EB68630cCd90C3152FB9Dee3a1C2A7201631D)) return 12105675798372;
        else if (contributor == address(0xe4F047C5DEB2659f3659057fe5cAFB5bC6bD4307)) return 8935141660703;
        else if (contributor == address(0x07bfeB5488ad97aA3920cf241E59d2A817054eA3)) return 7638104968020;
        else if (contributor == address(0xC3632CD03BEd246719965bB74279af79bE4bd813)) return 7638104968020;
        else if (contributor == address(0x0C0aB132F5a8d0988e88997cb2604F494052BDEF)) return 7205759403793;
        
        return 0;
    }
}