[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 4294967295 # 2^32-1
# solc = "0.8.20"
fs_permissions = [{ access = "read-write", path = "./"}]
# libraries = ["lib/v3-periphery/contracts/libraries/PoolAddress.sol:PoolAddress:0xD09971D8ed6C6a5e57581e90d593ee5B94e348D4"]

[fuzz]
seed = "0x02"
runs = 10000

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${RPC_MAINNET}"

[invariant]
fail_on_revert = true   # Fail the test if the contract reverts
runs           = 10   # Number of times that a sequence of function calls is generated and run
depth          = 100     # Number of function calls made in a given run.
