[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 20_000
# solc = "0.8.20"
fs_permissions = [{ access = "read-write", path = "./"}]
libraries = ["lib/v3-periphery/contracts/libraries/PoolAddress.sol:PoolAddress:0xD09971D8ed6C6a5e57581e90d593ee5B94e348D4"]
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[fuzz]
seed = "0x00"

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${RPC_MAINNET}"