[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 20000 # 2^32-1
solc = "0.8.28"
fs_permissions = [{ access = "read-write", path = "./"}, { access = "read-write", path = "./src/interfaces"}]
# libraries = ["lib/v3-periphery/contracts/libraries/PoolAddress.sol:PoolAddress:0xD09971D8ed6C6a5e57581e90d593ee5B94e348D4"]
gas_reports = ["Vault","Oracle"]
gas_limit = "18446744073709551615"
evm_version = "cancun"

[fuzz]
# seed = "0x10"
runs = 100

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
tarp_testnet = "${RPC_TARP}"

[invariant]
fail_on_revert = true   # Fail the test if the contract reverts
runs           = 5   # Number of times that a sequence of function calls is generated and run
depth          = 50     # Number of function calls made in a given run.
